@startuml
actor 管理员

usecase "编号零件" as 编号零件
usecase "命名零件类型" as 命名零件类型
usecase "记录零件价格" as 记录零件价格
usecase "查询组件价格" as 查询组件价格

管理员 --> 编号零件
管理员 --> 命名零件类型
管理员 --> 记录零件价格
管理员 --> 查询组件价格

' 查询组件价格 需要使用编号零件的信息，但根据约束不能 include 或 extend
' 查询组件价格 需要使用命名零件类型的信息，但根据约束不能 include 或 extend
' 查询组件价格 需要使用记录零件价格的信息，但根据约束不能 include 或 extend
' 记录零件价格 需要编号后的零件，但根据约束禁止 include 编号零件

@enduml
