@startuml
actor 用户

usecase "创建图形"
usecase "选择图形"
usecase "删除图形"
usecase "调整图形尺寸"
usecase "移动图形"
usecase "创建新图层"
usecase "图层导航"
usecase "等比例缩放"

用户 --> "创建图形"
用户 --> "选择图形"
用户 --> "删除图形"
用户 --> "调整图形尺寸"
用户 --> "移动图形"
用户 --> "创建新图层"
用户 --> "图层导航"
用户 --> "等比例缩放"

' 等比例缩放必须在执行时选择图形
"等比例缩放" ..> "选择图形" : <<include>>

' 当按住Shift时，调整图形尺寸扩展为等比例缩放
"等比例缩放" .> "调整图形尺寸" : <<extend>>
@enduml
