@startuml
actor 用户

usecase "软件初始启动" as UC1
usecase "创建图形" as UC2
usecase "选择图形" as UC3
usecase "删除图形" as UC4
usecase "改变图形尺寸" as UC5
usecase "移动图形" as UC6
usecase "创建图层" as UC7
usecase "管理图层" as UC8

用户 -> UC1
用户 -> UC2
用户 -> UC3
用户 -> UC4
用户 -> UC5
用户 -> UC6
用户 -> UC7
用户 -> UC8

' 创建图形时必定需要软件初始启动
UC2 ..> UC1 : include

' 删除图形时需要先选择图形
UC4 ..> UC3 : include

' 改变图形尺寸可选择在图形工具区域点击放大或缩小
UC5 .> UC2 : extend (图形工具区域点击放大或缩小)

' 移动图形可以在选择图形内部拖动
UC6 .> UC3 : extend (选择图形内部拖动)

' 在图形工具区域点击“新页”按钮可创建新图层
UC7 .> UC1 : extend (图形工具区域点击“新页”按钮)

' 切换多个图层进行管理
UC8 .> UC7 : extend (图形工具区域点击“下一页”按钮)

@enduml
