@startuml
actor User

usecase "启动软件" as UC1
usecase "创建图形" as UC2
usecase "选择图形" as UC3
usecase "删除图形" as UC4
usecase "改变尺寸" as UC5
usecase "移动图形" as UC6
usecase "创建图层" as UC7
usecase "管理图层" as UC8

User -> UC1
User -> UC2
User -> UC3
User -> UC4
User -> UC5
User -> UC6
User -> UC7
User -> UC8

' 创建图形需包含图形选择
UC2 ..> UC1 : include

' 选择图形功能在特定条件下可删除
UC4 ..> UC3 : extend 选择图形后点击删除元素

' 创建图层功能需管理图层
UC7 ..> UC8 : include

@enduml
