@startuml left to right direction
actor EditorOperator as E

usecase "启动图形编辑器" as UC1
usecase "创建图形" as UC2
usecase "创建自定义图形" as UC3
usecase "选择图形" as UC4
usecase "删除图形" as UC5
usecase "改变图形尺寸" as UC6
usecase "移动图形" as UC7
usecase "创建图层" as UC8
usecase "切换图层" as UC9

E --> UC1
E --> UC2
E --> UC3
E --> UC4
E --> UC5
E --> UC6
E --> UC7
E --> UC8
E --> UC9

' 当需要扩展自定义图形种类时，通过创建自定义图形功能扩展创建图形的支持类型
UC2 <|-- UC3 : extend
@enduml
