@startuml
actor 管理员

usecase "编号零件" as usecase1
usecase "命名零件类型" as usecase2
usecase "记录零件价格" as usecase3
usecase "查询组件价格" as usecase4

管理员 --> usecase1 : 编号零件
管理员 --> usecase2 : 命名零件类型
管理员 --> usecase3 : 记录零件价格
管理员 --> usecase4 : 查询组件价格

' 查询组件价格必须包含记录零件价格，因为组件价格依赖于零件价格的记录
usecase4 ..> usecase3 : include
' 查询组件价格必须包含编号零件，因为组件由已编号零件构成
usecase4 ..> usecase1 : include
' 查询组件价格必须包含命名零件类型，因为需通过类型识别零件
usecase4 ..> usecase2 : include

@enduml
